













 12%|████████████████████████████                                                                                                                                                                                                              | 12/100 [01:14<09:04,  6.19s/it]
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/home/iris/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/iris/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 198, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 737, in communicate_stop_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/home/iris/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/iris/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 180, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 749, in communicate_network_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/iris/paulshab/NLP_env/nlp_environ/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7f328f7bf320> (for pre_run_cell):